### ISSUE TITLE
Support Windows

### ISSUE THREAD

**Issue by mjashanks** [aletheia-foundation/aletheia-app#69]
Support for windows to include:

- [ ] Installation - scripted via powershell (?)
- [ ] Runtime - npm scripts
- [ ] Update documentation

Subtask of #13

**Comment by mjashanks** [comment]
I will look at this as I need it to start contributing!

**Comment by roo2** [comment]
Nice Mike, I'd consider working off the angular branch because it changes a lot about how we do the builds. all of the ./scripts are still the same but working on this branch will avoid duplicated work, In particular, I'd be interested to see if the electron build works for windows as it is now (`npm run electron:windows`)

**Comment by KadeMorton** [comment]
Close as duplicate to https://github.com/aletheia-foundation/aletheia-app/issues/13
